### ISSUE TITLE
Do you know where to rewrite the path to Lora?

### ISSUE THREAD

**Issue by bsdesigner** [Avaray/lora-keywords-finder#10]
The extension sees only the path to the main folder with Lora, but does not read subfolders:

![Снимок экрана 2024-10-27 142027](https://github.com/user-attachments/assets/dee4b826-b573-4398-adb4-5ee75c7aed02)

![Снимок экрана 2024-10-26 155656](https://github.com/user-attachments/assets/bc158bff-d6f7-4d23-962c-8dba734ba050)

**Comment by Avaray** [comment]
Did you update your extension?

**Comment by bsdesigner** [comment]
The update didn't help. Deleting the folder with the extension from Stable Diffusion WebUI Forge\extensions and reinstalling the extension again helped. Now everything works! Once again - thank you very much for your work!

**Comment by Avaray** [comment]
Your welcome.

Anyway, I need to investigate that. Thanks for all your feedbacks 👍
